
name: Deploy docs

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, docs ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
        
      - name: Install Bridget
        run: pip3 install -e .
      
      - name: Install Doc requirements
        run: pip install sphinx pydata_sphinx_theme sphinx-gallery sphinx_autodoc_typehints

      - name: Build docs
        run: | 
          cd doc
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: doc/_build/html
